### ISSUE TITLE
FileViewer Reload Issue--Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by james-chao** [densen2014/BootstrapBlazor.FileViewer#4]
第一次按View Reload時可出現Excel File
<img width="936" alt="image" src="https://github.com/densen2014/BootstrapBlazor.FileViewer/assets/3213919/56aa0b76-d302-4ba0-ba55-50bf5de79cc0">
再次按View Reload時出現 Object reference not set to an instance of an object.
<img width="958" alt="image" src="https://github.com/densen2014/BootstrapBlazor.FileViewer/assets/3213919/3d6e0010-2242-413d-9ff7-dea4c9bb97e0">

復原專案供參考
https://github.com/james-chao/FileViewerIssue.git

**Comment by densen2014** [comment]
感谢反馈

**Comment by densen2014** [comment]
确认是依赖包日期转换问题, 升级依赖包解决

**Comment by densen2014** [comment]
升级到新版试试

https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.2

**Comment by james-chao** [comment]
> 升级到新版试试
> 
> https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.2



> 升级到新版试试
> 
> https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.2

@densen2014 已升級8.0.2 但碰到錯誤如下:
Could not load file or assembly 'NPOI, Version=2.5.1.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1'. 系統找不到指定的檔案。 at ce.office.extension.ExcelHelper.ToHtml(String filePath) at BootstrapBlazor.Components.FileViewer.Refresh()

**Comment by densen2014** [comment]
可能版本发布错了。晚点再发布一版本

**Comment by densen2014** [comment]
8.0.3-beta1 对应npoi 2.5.6

8.0.3-beta2 对应npoi 2.6.1

两个版本你自己测测

我电脑上beta1运行没问题。beta2的2.6.1 有点问题

**Comment by james-chao** [comment]
> > 升级到新版试试
> > https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.2
> 
> > 升级到新版试试
> > https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.2
> 
> @densen2014 已升級8.0.2 但碰到錯誤如下: Could not load file or assembly 'NPOI, Version=2.5.1.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1'. 系統找不到指定的檔案。 at ce.office.extension.ExcelHelper.ToHtml(String filePath) at BootstrapBlazor.Components.FileViewer.Refresh()

新版8.0.2 是reference NPOI 2.7.0
![image](https://github.com/densen2014/BootstrapBlazor.FileViewer/assets/3213919/213fcd12-8a79-4a45-95e1-4db641e56cc9)

**Comment by james-chao** [comment]
> 8.0.3-beta1 对应npoi 2.5.6
> 
> 8.0.3-beta2 对应npoi 2.6.1
> 
> 两个版本你自己测测
> 
> 我电脑上beta1运行没问题。beta2的2.6.1 有点问题

@densen2014 感謝，剛開始測試beta1 beta2 皆可正常，但現在又出現以下錯誤了，可能版本又发布错了
Could not load file or assembly 'NPOI, Version=2.5.1.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1'. 系統找不到指定的檔案。 at ce.office.extension.ExcelHelper.ToHtml(String filePath) at BootstrapBlazor.Components.FileViewer.Refresh()

**Comment by densen2014** [comment]
这个事情很迷，因为依赖于这个库。你试一下在你的工程直接引用这个库。

**Comment by densen2014** [comment]
[BootstrapBlazor.FileViewer.zip](https://github.com/densen2014/BootstrapBlazor.FileViewer/files/15387105/BootstrapBlazor.FileViewer.zip)

你工程我发布的bin, 你试一试.

**Comment by densen2014** [comment]
> > 8.0.3-beta1 对应npoi 2.5.6
> > 8.0.3-beta2 对应npoi 2.6.1
> > 两个版本你自己测测
> > 我电脑上beta1运行没问题。beta2的2.6.1 有点问题
> 
> @densen2014 感謝，剛開始測試beta1 beta2 皆可正常，但現在又出現以下錯誤了，可能版本又发布错了 Could not load file or assembly 'NPOI, Version=2.5.1.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1'. 系統找不到指定的檔案。 at ce.office.extension.ExcelHelper.ToHtml(String filePath) at BootstrapBlazor.Components.FileViewer.Refresh()

你要理解一件事情, 发布的版本就是固定的. 既然debug没事, 那肯定没事. 自己多试试发布, 重新生成之类的操作

**Comment by densen2014** [comment]
https://www.nuget.org/packages/BootstrapBlazor.FileViewer/8.0.3-NPOI256

**Comment by james-chao** [comment]
> > > 8.0.3-beta1 对应npoi 2.5.6
> > > 8.0.3-beta2 对应npoi 2.6.1
> > > 两个版本你自己测测
> > > 我电脑上beta1运行没问题。beta2的2.6.1 有点问题
> > 
> > 
> > @densen2014 感謝，剛開始測試beta1 beta2 皆可正常，但現在又出現以下錯誤了，可能版本又发布错了 Could not load file or assembly 'NPOI, Version=2.5.1.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1'. 系統找不到指定的檔案。 at ce.office.extension.ExcelHelper.ToHtml(String filePath) at BootstrapBlazor.Components.FileViewer.Refresh()
> 
> 你要理解一件事情, 发布的版本就是固定的. 既然debug没事, 那肯定没事. 自己多试试发布, 重新生成之类的操作

@densen2014 感謝，重新update 8.0.3 現在可正常運作

**Comment by james-chao** [comment]
重新update 8.0.3 現在可正常運作
